# Generated by Django 5.2.6 on 2025-09-23 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeojsonFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('file', models.FileField(upload_to='geojson_files/', verbose_name='Файл')),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('layer', models.CharField(max_length=256, verbose_name='Слой')),
                ('year', models.IntegerField(default=2024, verbose_name='Год')),
                ('quarter', models.IntegerField(default=1, verbose_name='Квартал')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Цвет')),
                ('geojson_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MapServis.geojsonfiles', verbose_name='GeoJSON файл')),
            ],
        ),
    ]
